language: node_js
node_js:
  - 0.10
notifications:
    email: nick+travis@semenkovich.com
    on_success: change
    on_failure: change
before_install:
    - npm install -g grunt-cli
install:
    - npm install
before_script:
    - grunt build
